### PR TITLE
Add $FGC to example docker file, and fix list syntax

### PR DESCRIPTION
**Pull request by sanjayankur31**

### CODE REVIEW

**Comment by LorbusChris** [comment]
@sanjayankur31 what is $FGC? Is it the Fedora version number?
Wasn't the naming convention changed on the Fedora Registry to exclude the version number?

**Comment by sanjayankur31** [comment]
Yes, it's the Fedora version number.

I don't know if the change was made etc. The ticket here is still open:
https://pagure.io/ContainerSIG/container-sig/issue/2

I spoke to @cverna on IRC today and they pointed out that the compneuro container is not namespaced in the registry because the docker file is missing this `$FGC` in the "name" label:

- https://src.fedoraproject.org/container/compneuro
- https://koji.fedoraproject.org/koji/packageinfo?packageID=33055

I.e., at the moment, one cannot pull the f33 based compneuro image:

```
$ podman pull registry.fedoraproject.org/f33/compneuro
Trying to pull registry.fedoraproject.org/f33/compneuro:latest...
  manifest unknown: manifest unknown
Error: Error initializing source docker://registry.fedoraproject.org/f33/compneuro:latest: Error reading manifest latest in registry.fedoraproject.org/f33/compneuro: manifest unknown: manifest unknown

```

The fix is to add this, as is done here, for example: https://src.fedoraproject.org/container/python3/blob/rawhide/f/Dockerfile#_35

**Comment by sanjayankur31** [comment]
(Basically, we don't want users to be using rawhide based images---they should be able to use images based on stable Fedora releases)

**Comment by LorbusChris** [comment]
I was under the impression this namespacing had been removed already, but I might be wrong.
Either way, I would want to handle the different available image versions via tags, and not via different image names.

**Comment by sanjayankur31** [comment]
Sure, that's probably something for the SIG to discuss. In the meantime,
whats the method now that should be documented so that Fedora community
folks can build containers against different Fedora release base images
please?

**Comment by sanjayankur31** [comment]
I can confirm that using `$FGC` works. I don't know if it's necessary or what the right way of doing it without using `$FGC` is, but it works. I've used it to create the compneuro container image for rawhide, F34, and F33:

https://src.fedoraproject.org/container/compneuro

https://koji.fedoraproject.org/koji/packageinfo?packageID=33055

**Comment by cverna** [comment]
Yes after talking with @sanjayankur31, he had a case where the FGC was needed and since adding custom tags for a container is still not super trivial nor documented I think it makes sense to document back FGC.
It would still be nice to push the removal of it, but I don't have the time for that :(

**Pull request merged**
